import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ProfilePic from "../../public/images/profile/Anjulata.png";
import Layout from "@/components/Layout";
import Animatedtext from "@/components/Animatedtext";
import Hireme from "@/components/Hireme";
import LinkArrow from "@/components/Icons";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import Transition from "@/components/Transition";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Transition/>
      <main className="flex items-center min-h-screen text-dark w-full ">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex justify-between item-center w-full lg:flex-col">
            <div className="w-1/2 md:w-full md:mb-2">
              <Image
                src={ProfilePic}
                alt="profile"
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                priority
                className="w-full h-auto relative -left-15 mt-10 lg:hidden md:inline-block md:w-full "
              ></Image>
            </div>
            <div className="w-1/3 flex flex-col justify-center items-center self-center lg:w-full lg:text-center">
              <Animatedtext
                className="!text-3xl !text-left xl:!text-5xl lg:!text-center lg:text-6xl md:text-5xl sm:!text-3xl"
                text="Empowering Minds, Shaping Futures through Knowledge and guidance."
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled professor, I am dedicated to turning ideas into
                reality. Explore my journey through groundbreaking research in
                IoT and wireless technologies and impactful teaching
                experiences.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center ">
                <Link
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg 
            font-semibold hover:bg-light hover:text-dark border border-solid 
            border-transparent hover:border-2 hover:border-dark lg:self-center md:p-2 md:px-4 md:text-base"
                  target="_blank"
                  href="https://www.sgsits.ac.in/index.php/people-ec/ete-faculty-members/545-mrs-anjulata-yadav"
                >
                  Resume
                  {/* <LinkArrow className='ml-1 w-6' />  */}
                </Link>
                <Link
                  className="ml-4 text-lg font-medium capitalize text-dark underline md:text-base"
                  target="_blank"
                  href="mailto:yadawanjulata@gmail.com"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <Hireme />
        <div className="absolute right-8 bottom-2 inline-block w-20">
          <Image src={lightBulb} alt="anjulata" className="w-full h-auto md:hidden" />
        </div>
      </main>
    </>
  );
}
